### ISSUE TITLE
Error with no messages

### ISSUE THREAD

**Issue by mustafa519** [dominicbirch/bundle-declarations-webpack-plugin#15]
Hello,

I tried to use this plugin for my webpack, however I am getting a weird error. Seems like the compiler cannot catch the async error in the nextTick due to in a worker thread.

```bash
node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
Error: Compiled with errors
    at checkDiagnosticsErrors (/Users/xxx/services/_dev/node_modules/dts-bundle-generator/dist/helpers/check-diagnostics-errors.js:22:11)

...

    at Object.<anonymous> (/Users/xxx/services/_dev/node_modules/bundle-declarations-webpack-plugin/dist/worker.1dcdb40d.cjs:1:1046)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
Emitted 'error' event on E instance at:
    at Worker.<anonymous> (/Users/xxx/services/_dev/node_modules/bundle-declarations-webpack-plugin/dist/index.cjs:1:2498)

```

Thanks.

**Comment by Threebow** [comment]
Getting the same error, but with a lot longer of a stack trace, and with no helpful error message unlike your output which at least contains a mention of nextTick.

Here is my full build log (modified to remove my absolute filesystem paths). Apologies if this is extraneous, but I felt it necessary to post seeing as there is no information in the error that hints to an issue in my code, and my build succeeds without this plugin with no other changes.

```
asset index.js 9.9 KiB [emitted] [javascript module] [minimized] (name: main) 1 related asset
orphan modules 313 bytes [orphan] 10 modules
runtime modules 2.44 KiB 3 modules
modules by path ./src/ 12.4 KiB
  modules by path ./src/helpers/ 8.6 KiB 15 modules
  modules by path ./src/stdlib/*.ts 1.79 KiB
    ./src/stdlib/index.ts 88 bytes [built] [code generated]
    + 3 modules
  modules by path ./src/*.ts 1.96 KiB
    ./src/index.client.ts 435 bytes [built] [code generated]
    + 2 modules
external "lodash-es" 42 bytes [built] [code generated]
external "luxon" 42 bytes [built] [code generated]
external "vue" 42 bytes [built] [code generated]
external "@sentry/browser" 42 bytes [built] [code generated]

LOG from BundleDeclarationsWebpackPlugin
<w> Failed to create .d.ts Error: Compiled with errors
<w>     at checkDiagnosticsErrors (./node_modules\.pnpm\dts-bundle-generator@9.2.5\node_modules\dts-bundle-generator\dist\helpers\check-diagnostics-errors.js:21:11)
<w>     at checkProgramDiagnosticsErrors (./node_modules\.pnpm\dts-bundle-generator@9.2.5\node_modules\dts-bundle-generator\dist\helpers\check-diagnostics-errors.js:12:5)
<w>     at getDeclarationFiles (./node_modules\.pnpm\dts-bundle-generator@9.2.5\node_modules\dts-bundle-generator\dist\compile-dts.js:128:66)
<w>     at compileDts (./node_modules\.pnpm\dts-bundle-generator@9.2.5\node_modules\dts-bundle-generator\dist\compile-dts.js:37:22)
<w>     at generateDtsBundle (./node_modules\.pnpm\dts-bundle-generator@9.2.5\node_modules\dts-bundle-generator\dist\bundle-generator.js:14:74)
<w>     at ./node_modules\.pnpm\bundle-declarations-webpack-plugin@5.0.1_webpack@5.90.1\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:999
<w>     at new Promise (<anonymous>)
<w>     at l (./node_modules\.pnpm\bundle-declarations-webpack-plugin@5.0.1_webpack@5.90.1\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:946)
<w>     at ./node_modules\.pnpm\bundle-declarations-webpack-plugin@5.0.1_webpack@5.90.1\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:2815
<w>     at fn (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:537:19)
<w>     at Hook.eval [as callAsync] (eval at create (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:59:17)
<w>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
<w>     at cont (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3072:34)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3120:10
<w>     at symbolIterator (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3485:9)
<w>     at done (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3527:9)
<w>     at ./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2830:7
<w>     at done (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2865:11)
<w>     at ./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2818:7
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:4674:18
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\HookWebpackError.js:68:3
<w>     at Hook.eval [as callAsync] (eval at create (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<w>     at Cache.store (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Cache.js:107:20)
<w>     at ItemCacheFacade.store (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\CacheFacade.js:141:15)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:4671:25
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Cache.js:93:5
<w>     at Hook.eval [as callAsync] (eval at create (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<w>     at Cache.get (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Cache.js:75:18)
<w>     at ItemCacheFacade.get (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\CacheFacade.js:115:15)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:4580:22
<w>     at arrayEach (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2405:9)
<w>     at Object.each (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2846:9)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:4569:14
<w>     at symbolIterator (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3482:9)
<w>     at timesSync (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2297:7)
<w>     at Object.eachLimit (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3463:5)
<w>     at Compilation.createChunkAssets (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:4546:12)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3115:14
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3296:6
<w>     at ./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2818:7
<w>     at done (./node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3522:9)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3259:8
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3369:32
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\HookWebpackError.js:68:3
<w>     at Hook.eval [as callAsync] (eval at create (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<w>     at Cache.store (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Cache.js:107:20)
<w>     at ItemCacheFacade.store (./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\CacheFacade.js:141:15)
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Compilation.js:3369:11
<w>     at ./node_modules\.pnpm\webpack@5.90.1_esbuild@0.20.0_webpack-cli@5.1.4\node_modules\webpack\lib\Cache.js:93:5
<w>     at Hook.eval [as callAsync] (eval at create (./node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
+ 1 hidden lines

webpack 5.90.1 compiled successfully in 9093 ms
```

Additionally, while Webpack says the build has compiled successfully, there are no typings generated. I would expect this to fail the entire build, instead of allowing it to pass.

Please advise if I should open a different issue. It seems related to this one as the error message is the same, so I will leave this here for now.

**Comment by dominicbirch** [comment]
Thanks for bringing these to my attention, sorry it's taken a while to notice the issue :sweat_smile: 

So essentially @Threebow  is saying that it would be better to fail the _whole_ build rather than to allow it to complete without declarations?  Makes sense to me.

For what @mustafa519 is seeing, I will look into catching this and failing the compilation in a consistent way.

**Comment by dominicbirch** [comment]
Happy to pick both up against this issue by the way :smile:

**Comment by dominicbirch** [comment]
Hi,

So just by way of an update on this; it was not possible to fail the compilation from the worker thread by design (had to look at the code to remember why I changed this).  The idea was to speed up the feedback when working on complex apps in watch mode by taking the dts bundle generation out of process, and having a delayed feedback in this instance.  In a plain (not webpack watching) compilation context, it does work as you want; so what I've done is add in the next version `5.1.1` a new boolean option for the plugin `blockingWatch` which will allow you to override the watch mode behaviour to match that of the non-watch default behaviour (meaning that it blocks and if necessary fails the compilation).

It will be undesirable to do this in a lot of cases, but appreciate sometimes you will want to either know it's all worked or for it not to work with an error, hope this is ok for both your needs :sweat_smile:
